#!/usr/bin/perl
###########################################
# login 
# 2006, Mike Schilli <cpan@perlmeister.com>
###########################################
use strict;
use warnings;
use Getopt::Std;
use Pod::Usage;

use Log::Log4perl qw(:easy);
use WWW::Mechanize::Pluggable;
Log::Log4perl->easy_init($DEBUG);

my $mech = new WWW::Mechanize::Pluggable;

$mech->get("http://forums.slickdeals.net/");
#$mech->phpbb_login("testuser1", "t1");
my $forums = $mech->phpbb_forums();

#$mech->phpbb_forum_enter(qr(^USArundbrief Forum$));
#$mech->phpbb_topics();

__END__

=head1 NAME

    login - blah blah blah

=head1 SYNOPSIS

    login -xyz

=head1 OPTIONS

=over 8

=item B<-x>

Prints this manual page in text format.

=back

=head1 DESCRIPTION

login blah blah blah.

=head1 EXAMPLES

  $ login -x foo bar

=head1 LEGALESE

Copyright 2006 by Mike Schilli, all rights reserved.
This program is free software, you can redistribute it and/or
modify it under the same terms as Perl itself.

=head1 AUTHOR

2006, Mike Schilli <cpan@perlmeister.com>
