#!/usr/bin/perl -w
###########################################
# xx -- 
# Mike Schilli, 2005 (m@perlmeister.com)
###########################################
use strict;
use Sysadm::Install qw(:all);

use WWW::Mechanize::Pluggable;
    my $mech = new WWW::Mechanize::Pluggable;

        $mech->get("http://usarundbrief.com/forum");
#$mech->phpbb_login("username", "password");

                    # Get a list of forums
                my $forums = $mech->phpbb_forums();
                    for my $forum (@$forums) {
                                print "Forum:", $forum->text(), "\n";
                                    }

        # Enter a forum matched by a regex
    $mech->phpbb_forum_enter(qr(.));

            # Return a list of topics
        my $topics = $mech->phpbb_topics();
            for my $topic (@$topics) {
                        print "headline=$topic->{text} url=$topic->{url}\n";
                            }
